"""Real METAR weather from the ATMOS-X CLI.

The CLI is a third-party executable that talks to the network, so nothing here runs it:
what is tested is everything around it -- reading what it writes, picking the station to
ask for, choosing which day to ask about, and copying the result onto a mission.
"""

from __future__ import annotations

import csv
from datetime import datetime, timedelta
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest
from dcs.weather import Weather

from game.missiongenerator.atmosxliveweather import (
    PresetParseError,
    Station,
    apply_weather,
    choose_station,
    clock_from,
    observation_date_for,
    parse_preset,
    stations_for_theater,
)

# Trimmed from a real "atmosx-cli metar LCLK --save" run: comments, the trailing
# "-- end of vdata" markers and the two top-level assignments the reader must cope with.
PRESET = """\
-- Weather preset: ATX - LCLK METAR
-- Generated by ATMOS-X CLI: 2026-08-19 11:30:07

vdata = {
    name = "ATX - LCLK METAR",
    atmosphere_type = 0,
    groundTurbulence = 0.0000,
    enable_dust = false,
    dust_density = 0,
    qnh = 758,
    season = {
        temperature = 31.0,
    },
    visibility = {
        distance = 80000,
    },
    wind = {
        atGround = { speed = 3.60, dir = 350, },
        at2000 = { speed = 4.32, dir = 350, },
        at8000 = { speed = 5.40, dir = 350, },
    },
    clouds = {
        preset = "none",
        thickness = 0,
        density = 0,
        base = 764,
        iprecptns = 0,
    },
    fog2 = {
        mode = 1,
        manual = {
        },
    },
} -- end of vdata
dtime = {
    date = {
        Year = 2026,
        Day = 19,
        Month = 8,
    },
    start_time = 43200,
} -- end of dtime
"""


def test_reads_both_top_level_blocks() -> None:
    parsed = parse_preset(PRESET)
    assert set(parsed) == {"vdata", "dtime"}
    assert parsed["vdata"]["qnh"] == 758
    assert parsed["vdata"]["clouds"]["preset"] == "none"
    assert parsed["vdata"]["enable_dust"] is False
    assert parsed["vdata"]["wind"]["atGround"] == {"speed": 3.6, "dir": 350}
    assert parsed["vdata"]["fog2"]["manual"] == {}


def test_a_malformed_preset_is_an_error_not_a_wrong_answer() -> None:
    with pytest.raises(PresetParseError):
        parse_preset("vdata = { qnh = ")


def test_the_clock_is_read_separately_from_the_weather() -> None:
    assert clock_from(parse_preset(PRESET)["dtime"]) == datetime(2026, 8, 19, 12, 0)


def test_the_observation_lands_on_the_mission() -> None:
    weather = Weather("Syria")
    apply_weather(weather, parse_preset(PRESET)["vdata"])
    assert weather.qnh == 758
    assert weather.season_temperature == 31.0
    assert weather.visibility_distance == 80000
    assert weather.clouds_base == 764
    assert weather.clouds_preset == "none"
    assert weather.wind_at_ground.speed == 3.6
    assert weather.wind_at_8000.direction == 350


def test_fields_a_metar_says_nothing_about_are_left_alone() -> None:
    """The preset is not a whole weather definition; what it omits the campaign keeps."""
    weather = Weather("Syria")
    halo, cyclones = weather.halo, weather.cyclones
    weather.type_weather = 2
    apply_weather(weather, parse_preset(PRESET)["vdata"])
    assert weather.halo is halo
    assert weather.cyclones is cyclones
    assert weather.type_weather == 2


# --- station selection -----------------------------------------------------------


@pytest.fixture
def cli(tmp_path: Path) -> Path:
    """A stand-in CLI: only its folder matters, for finding dcs_icao.csv beside it."""
    rows = [
        ["Map", "Airfield", "ICAO", ""],
        ["Syria", "Larnaca International", "LCLK", ""],
        ["Syria", "Adana Şakirpaşa Airport", "LTAF", ""],
        ["Syria", "Rayak Air Base", "OLRA", ""],
        ["Caucasus", "Batumi", "UGSB", ""],
        ["Syria", "No Station", "", ""],
    ]
    with (tmp_path / "dcs_icao.csv").open("w", newline="", encoding="utf-8-sig") as f:
        csv.writer(f).writerows(rows)
    exe = tmp_path / "atmosx-cli.exe"
    exe.write_text("", encoding="utf-8")
    return exe


def test_only_stations_on_this_terrain_and_only_real_ones(cli: Path) -> None:
    stations = stations_for_theater(cli, "Syria")
    assert [s.icao for s in stations] == ["LCLK", "LTAF", "OLRA"]
    assert Station("UGSB", "Batumi") not in stations


def test_an_airfield_that_reports_is_used(cli: Path) -> None:
    station = choose_station(cli, "Syria", ["Larnaca International"])
    assert station is not None and station.icao == "LCLK"


def test_names_match_across_accents_and_suffixes(cli: Path) -> None:
    """ED writes "Adana Sakirpasa", ATMOS-X writes "Adana Şakirpaşa Airport"."""
    station = choose_station(cli, "Syria", ["Adana Sakirpasa"])
    assert station is not None and station.icao == "LTAF"


def test_a_base_with_no_station_falls_back_to_the_nearest_that_has_one(
    cli: Path,
) -> None:
    positions = {
        "Beirut": SimpleNamespace(x=0.0, y=0.0),
        "Rayak Air Base": SimpleNamespace(x=1000.0, y=0.0),
        "Larnaca International": SimpleNamespace(x=500_000.0, y=0.0),
    }
    station = choose_station(cli, "Syria", ["Beirut"], positions)
    assert station is not None and station.icao == "OLRA"


def test_without_positions_it_still_answers(cli: Path) -> None:
    station = choose_station(cli, "Syria", ["Nowhere"])
    assert station is not None


def test_a_terrain_atmosx_does_not_cover_has_no_station(cli: Path) -> None:
    assert choose_station(cli, "Marianas", ["Andersen"]) is None


def test_a_missing_csv_is_survivable(tmp_path: Path) -> None:
    assert stations_for_theater(tmp_path / "atmosx-cli.exe", "Syria") == []


# --- which day to ask about ------------------------------------------------------

_NOW = datetime(2026, 8, 19, 12, 0)


@pytest.mark.parametrize(
    "mission_time,expected",
    [
        pytest.param(_NOW, _NOW.date(), id="a mission set today uses today"),
        pytest.param(
            _NOW - timedelta(days=10),
            (_NOW - timedelta(days=10)).date(),
            id="within the archive, its own day",
        ),
        pytest.param(
            datetime(2030, 6, 2, 9, 0),
            (_NOW - timedelta(days=1)).date(),
            id="a future campaign falls back to yesterday",
        ),
        pytest.param(
            _NOW - timedelta(days=40),
            (_NOW - timedelta(days=1)).date(),
            id="older than the archive falls back to yesterday",
        ),
    ],
)
def test_observation_date(mission_time: datetime, expected: Any) -> None:
    chosen = observation_date_for(mission_time, _NOW)
    assert chosen is not None and chosen.date() == expected


# --- the settings only appear when they can do something -------------------------


def test_the_atmosx_settings_hide_unless_that_pack_is_selected() -> None:
    """Four settings that quietly do nothing are worse than four settings not shown."""
    from game.settings import Settings
    from game.settings.settings import CloudPresetPack

    settings = Settings()
    guarded = {
        name: description
        for name, description in Settings.fields("Campaign Management", "General")
        if name.startswith("atmosx_")
    }
    assert set(guarded) == {
        "atmosx_live_weather",
        "atmosx_live_weather_time",
        "atmosx_cli_path",
        "atmosx_metar_station",
    }

    predicates = []
    for description in guarded.values():
        assert description.visible_when is not None
        predicates.append(description.visible_when)

    settings.cloud_preset_pack = CloudPresetPack.ATMOSX
    settings.atmosx_live_weather = True  # the clock asks for this one too
    assert all(predicate(settings) for predicate in predicates)

    for pack in (
        CloudPresetPack.NONE,
        CloudPresetPack.BANDIT,
        CloudPresetPack.WEATHER2,
    ):
        settings.cloud_preset_pack = pack
        assert not any(predicate(settings) for predicate in predicates)


def test_the_clock_choice_hides_until_live_weather_is_on() -> None:
    """Choosing between two clocks for weather you are not fetching is noise."""
    from game.settings import Settings
    from game.settings.settings import CloudPresetPack

    settings = Settings()
    clock = dict(Settings.fields("Campaign Management", "General"))[
        "atmosx_live_weather_time"
    ]
    assert clock.visible_when is not None

    settings.cloud_preset_pack = CloudPresetPack.ATMOSX
    settings.atmosx_live_weather = False
    assert not clock.visible_when(settings)

    settings.atmosx_live_weather = True
    assert clock.visible_when(settings)

    settings.cloud_preset_pack = CloudPresetPack.BANDIT
    assert not clock.visible_when(settings)
