-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the Splash Damage 3.4.7 Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- SD3 plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.splashdamage3 then
            env.info("DCSRetribution|Splash Damage 3.4.7 plugin - Setting Up")
            splash_damage_options.game_messages = dcsRetribution.plugins.splashdamage3.game_messages
            splash_damage_options.debug = dcsRetribution.plugins.splashdamage3.debug
            splash_damage_options.weapon_missing_message = dcsRetribution.plugins.splashdamage3.weapon_missing_message
            splash_damage_options.enable_radio_menu = dcsRetribution.plugins.splashdamage3.enable_radio_menu
            splash_damage_options.wave_explosions = dcsRetribution.plugins.splashdamage3.wave_explosions
            splash_damage_options.larger_explosions = dcsRetribution.plugins.splashdamage3.larger_explosions
            splash_damage_options.use_dynamic_blast_radius = dcsRetribution.plugins.splashdamage3.use_dynamic_blast_radius
            splash_damage_options.dynamic_blast_radius_modifier = dcsRetribution.plugins.splashdamage3.dynamic_blast_radius_modifier / 100
            splash_damage_options.damage_model = dcsRetribution.plugins.splashdamage3.damage_model
            splash_damage_options.static_damage_boost = dcsRetribution.plugins.splashdamage3.static_damage_boost
            splash_damage_options.overall_scaling = dcsRetribution.plugins.splashdamage3.overall_scaling / 100
            splash_damage_options.unit_disabled_health = dcsRetribution.plugins.splashdamage3.unit_disabled_health
            splash_damage_options.unit_cant_fire_health = dcsRetribution.plugins.splashdamage3.unit_cant_fire_health
            splash_damage_options.infantry_cant_fire_health = dcsRetribution.plugins.splashdamage3.infantry_cant_fire_health
            splash_damage_options.cluster_enabled = dcsRetribution.plugins.splashdamage3.cluster_enabled
            splash_damage_options.cluster_bomblet_reductionmodifier = dcsRetribution.plugins.splashdamage3.cluster_bomblet_reduction_modifier
            splash_damage_options.cluster_bomblet_damage_modifier = dcsRetribution.plugins.splashdamage3.cluster_bomblet_damage_modifier
            splash_damage_options.rocket_multiplier = dcsRetribution.plugins.splashdamage3.rocket_multiplier
            splash_damage_options.shipRadarDamageEnable = dcsRetribution.plugins.splashdamage3.shipRadarDamageEnable
            splash_damage_options.oca_aircraft_damage_boost = dcsRetribution.plugins.splashdamage3.oca_aircraft_damage_boost
            splash_damage_options.ordnance_protection = dcsRetribution.plugins.splashdamage3.ordnance_protection
            splash_damage_options.ordnance_protection_radius = dcsRetribution.plugins.splashdamage3.ordnance_protection_radius
            splash_damage_options.detect_ordnance_destruction = dcsRetribution.plugins.splashdamage3.detect_ordnance_destruction
            splash_damage_options.snap_to_ground_if_destroyed_by_large_explosion = dcsRetribution.plugins.splashdamage3.snap_to_ground_if_destroyed_by_large_explosion
            splash_damage_options.max_snapped_height = dcsRetribution.plugins.splashdamage3.max_snapped_height
            splash_damage_options.recent_large_explosion_snap = dcsRetribution.plugins.splashdamage3.recent_large_explosion_snap
            splash_damage_options.recent_large_explosion_range = dcsRetribution.plugins.splashdamage3.recent_large_explosion_range
            splash_damage_options.recent_large_explosion_time = dcsRetribution.plugins.splashdamage3.recent_large_explosion_time
            splash_damage_options.groundunitordnance_damage_modifier = dcsRetribution.plugins.splashdamage3.groundunitordnance_damage_modifier
            splash_damage_options.groundunitordnance_blastwave_modifier = dcsRetribution.plugins.splashdamage3.groundunitordnance_blastwave_modifier
            splash_damage_options.CriticalComponent = dcsRetribution.plugins.splashdamage3.CriticalComponent
            splash_damage_options.CriticalComponent_Chance = dcsRetribution.plugins.splashdamage3.CriticalComponent_Chance
            splash_damage_options.CriticalComponent_Explosion_Power = dcsRetribution.plugins.splashdamage3.CriticalComponent_Explosion_Power
            splash_damage_options.only_players_weapons = dcsRetribution.plugins.splashdamage3.only_players_weapons
            splash_damage_options.blast_search_radius = dcsRetribution.plugins.splashdamage3.blast_search_radius
            splash_damage_options.apply_shaped_charge_effects = dcsRetribution.plugins.splashdamage3.apply_shaped_charge_effects
            splash_damage_options.cascade_scaling = dcsRetribution.plugins.splashdamage3.cascade_scaling
            splash_damage_options.cascade_explode_threshold = dcsRetribution.plugins.splashdamage3.cascade_explode_threshold
            splash_damage_options.always_cascade_explode = dcsRetribution.plugins.splashdamage3.always_cascade_explode
            splash_damage_options.damage_model_game_messages = dcsRetribution.plugins.splashdamage3.damage_model_game_messages
            splash_damage_options.enable_cargo_effects = dcsRetribution.plugins.splashdamage3.enable_cargo_effects
            splash_damage_options.debris_effects = dcsRetribution.plugins.splashdamage3.debris_effects
            splash_damage_options.cookoff_flares_enabled = dcsRetribution.plugins.splashdamage3.cookoff_flares_enabled
            splash_damage_options.smokeandcookoffeffectallvehicles = dcsRetribution.plugins.splashdamage3.smokeandcookoffeffectallvehicles
            splash_damage_options.allunits_enable_smoke = dcsRetribution.plugins.splashdamage3.allunits_enable_smoke
            splash_damage_options.allunits_enable_cookoff = dcsRetribution.plugins.splashdamage3.allunits_enable_cookoff
            splash_damage_options.allunits_cookoff_chance = dcsRetribution.plugins.splashdamage3.allunits_cookoff_chance
            splash_damage_options.allunits_smoke_chance = dcsRetribution.plugins.splashdamage3.allunits_smoke_chance
            splash_damage_options.track_groundunitordnance = dcsRetribution.plugins.splashdamage3.track_groundunitordnance
            splash_damage_options.napalm_mk77_enabled = dcsRetribution.plugins.splashdamage3.napalm_mk77_enabled
            splash_damage_options.napalm_unitdamage_enable = dcsRetribution.plugins.splashdamage3.napalm_unitdamage_enable
            splash_damage_options.napalm_doublewide_enabled = dcsRetribution.plugins.splashdamage3.napalm_doublewide_enabled
            splash_damage_options.trophy_enabled = dcsRetribution.plugins.splashdamage3.trophy_enabled
            splash_damage_options.track_pre_explosion_agl_gate = dcsRetribution.plugins.splashdamage3.track_pre_explosion_agl_gate
            splash_damage_options.track_pre_explosion_agl_limit = dcsRetribution.plugins.splashdamage3.track_pre_explosion_agl_limit
            splash_damage_options.cookoff_final_explosion_enabled = dcsRetribution.plugins.splashdamage3.cookoff_final_explosion_enabled
            splash_damage_options.cookoff_final_explosion_allunits_chance = dcsRetribution.plugins.splashdamage3.cookoff_final_explosion_allunits_chance
            splash_damage_options.cookoff_final_explosion_power = dcsRetribution.plugins.splashdamage3.cookoff_final_explosion_power
            splash_damage_options.napalm_continuousdamage_enable = dcsRetribution.plugins.splashdamage3.napalm_continuousdamage_enable
            splash_damage_options.napalm_continuousdamage_cooldown_seconds = dcsRetribution.plugins.splashdamage3.napalm_continuousdamage_cooldown_seconds
            splash_damage_options.napalm_continuousdamage_max_damage_instances_per_unit = dcsRetribution.plugins.splashdamage3.napalm_continuousdamage_max_damage_instances_per_unit
            splash_damage_options.megasmoke_enabled = dcsRetribution.plugins.splashdamage3.megasmoke_enabled
            splash_damage_options.megasmoke_radius = dcsRetribution.plugins.splashdamage3.megasmoke_radius
            splash_damage_options.megasmoke_layer_count = dcsRetribution.plugins.splashdamage3.megasmoke_layer_count
            splash_damage_options.megasmoke_smoke_time = dcsRetribution.plugins.splashdamage3.megasmoke_smoke_time
        end
    end
end
