"""Real METAR weather from the ATMOS-X CLI.

The CLI is a third-party executable that talks to the network, so nothing here runs it:
what is tested is everything around it -- reading what it writes, picking the station to
ask for, choosing which day to ask about, and copying the result onto a mission.
"""

from __future__ import annotations

import csv
from datetime import datetime, timedelta
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest
from dcs.weather import Weather

from dcs.cloud_presets import CLOUD_PRESETS
from dcs.weather import Weather as PydcsWeather

from game.weather.atmosxliveweather import (
    LiveWeather,
    PresetParseError,
    Station,
    apply_weather,
    choose_station,
    parse_preset,
    stations_for_theater,
)

# Trimmed from a real "atmosx-cli metar LCLK --save" run: comments, the trailing
# "-- end of vdata" markers and the two top-level assignments the reader must cope with.
PRESET = """\
-- Weather preset: ATX - LCLK METAR
-- Generated by ATMOS-X CLI: 2026-08-19 11:30:07

vdata = {
    name = "ATX - LCLK METAR",
    atmosphere_type = 0,
    groundTurbulence = 0.0000,
    enable_dust = false,
    dust_density = 0,
    qnh = 758,
    season = {
        temperature = 31.0,
    },
    visibility = {
        distance = 80000,
    },
    wind = {
        atGround = { speed = 3.60, dir = 350, },
        at2000 = { speed = 4.32, dir = 350, },
        at8000 = { speed = 5.40, dir = 350, },
    },
    clouds = {
        preset = "none",
        thickness = 0,
        density = 0,
        base = 764,
        iprecptns = 0,
    },
    fog2 = {
        mode = 1,
        manual = {
        },
    },
} -- end of vdata
dtime = {
    date = {
        Year = 2026,
        Day = 19,
        Month = 8,
    },
    start_time = 43200,
} -- end of dtime
"""


def test_reads_both_top_level_blocks() -> None:
    """dtime is parsed and then ignored -- the mission always keeps its own clock."""
    parsed = parse_preset(PRESET)
    assert set(parsed) == {"vdata", "dtime"}
    assert parsed["vdata"]["qnh"] == 758
    assert parsed["vdata"]["clouds"]["preset"] == "none"
    assert parsed["vdata"]["enable_dust"] is False
    assert parsed["vdata"]["wind"]["atGround"] == {"speed": 3.6, "dir": 350}
    assert parsed["vdata"]["fog2"]["manual"] == {}


def test_a_malformed_preset_is_an_error_not_a_wrong_answer() -> None:
    with pytest.raises(PresetParseError):
        parse_preset("vdata = { qnh = ")


def test_the_observation_lands_on_the_mission() -> None:
    weather = Weather("Syria")
    apply_weather(weather, parse_preset(PRESET)["vdata"])
    assert weather.qnh == 758
    assert weather.season_temperature == 31.0
    assert weather.visibility_distance == 80000
    assert weather.wind_at_ground.speed == 3.6
    assert weather.wind_at_8000.direction == 350
    # A clear METAR: preset "none" means no preset, not a preset called "none".
    assert weather.clouds_preset is None
    assert weather.clouds_base == 0


def test_the_mission_can_still_be_written_out() -> None:
    """The regression that matters: DCS reads .name off the preset and validates the
    base against it, so a preset key left as a bare string kills mission generation."""
    for key, base in (("none", 764), ("Preset10", 2000)):
        vdata = parse_preset(PRESET)["vdata"]
        vdata["clouds"] = {
            "preset": key,
            "base": base,
            "thickness": 0,
            "density": 0,
            "iprecptns": 0,
        }
        weather = Weather("Syria")
        apply_weather(weather, vdata)
        assert isinstance(weather.dict(), dict)


def test_a_ceiling_outside_the_presets_range_is_clamped_not_fatal() -> None:
    """DCS refuses the mission outright; a METAR ceiling near the edge is common."""
    preset = CLOUD_PRESETS["Preset10"].value
    vdata = parse_preset(PRESET)["vdata"]
    vdata["clouds"] = {
        "preset": "Preset10",
        "base": 1,
        "thickness": 0,
        "density": 0,
        "iprecptns": 0,
    }
    weather = Weather("Syria")
    apply_weather(weather, vdata)
    assert weather.clouds_base >= preset.min_base
    assert isinstance(weather.dict(), dict)


def test_fields_a_metar_says_nothing_about_are_left_alone() -> None:
    """The preset is not a whole weather definition; what it omits the campaign keeps."""
    weather = Weather("Syria")
    halo, cyclones = weather.halo, weather.cyclones
    weather.type_weather = 2
    apply_weather(weather, parse_preset(PRESET)["vdata"])
    assert weather.halo is halo
    assert weather.cyclones is cyclones
    assert weather.type_weather == 2


# --- station selection -----------------------------------------------------------


@pytest.fixture
def cli(tmp_path: Path) -> Path:
    """A stand-in CLI: only its folder matters, for finding dcs_icao.csv beside it."""
    rows = [
        ["Map", "Airfield", "ICAO", ""],
        ["Syria", "Larnaca International", "LCLK", ""],
        ["Syria", "Adana Şakirpaşa Airport", "LTAF", ""],
        ["Syria", "Rayak Air Base", "OLRA", ""],
        ["Caucasus", "Batumi", "UGSB", ""],
        ["Syria", "No Station", "", ""],
    ]
    with (tmp_path / "dcs_icao.csv").open("w", newline="", encoding="utf-8-sig") as f:
        csv.writer(f).writerows(rows)
    exe = tmp_path / "atmosx-cli.exe"
    exe.write_text("", encoding="utf-8")
    return exe


def test_only_stations_on_this_terrain_and_only_real_ones(cli: Path) -> None:
    stations = stations_for_theater(cli, "Syria")
    assert [s.icao for s in stations] == ["LCLK", "LTAF", "OLRA"]
    assert Station("UGSB", "Batumi") not in stations


def test_an_airfield_that_reports_is_used(cli: Path) -> None:
    station = choose_station(cli, "Syria", ["Larnaca International"])
    assert station is not None and station.icao == "LCLK"


def test_names_match_across_accents_and_suffixes(cli: Path) -> None:
    """ED writes "Adana Sakirpasa", ATMOS-X writes "Adana Şakirpaşa Airport"."""
    station = choose_station(cli, "Syria", ["Adana Sakirpasa"])
    assert station is not None and station.icao == "LTAF"


def test_a_base_with_no_station_falls_back_to_the_nearest_that_has_one(
    cli: Path,
) -> None:
    positions = {
        "Beirut": SimpleNamespace(x=0.0, y=0.0),
        "Rayak Air Base": SimpleNamespace(x=1000.0, y=0.0),
        "Larnaca International": SimpleNamespace(x=500_000.0, y=0.0),
    }
    station = choose_station(cli, "Syria", ["Beirut"], positions)
    assert station is not None and station.icao == "OLRA"


def test_without_positions_it_still_answers(cli: Path) -> None:
    station = choose_station(cli, "Syria", ["Nowhere"])
    assert station is not None


def test_a_terrain_atmosx_does_not_cover_has_no_station(cli: Path) -> None:
    assert choose_station(cli, "Marianas", ["Andersen"]) is None


def test_a_missing_csv_is_survivable(tmp_path: Path) -> None:
    assert stations_for_theater(tmp_path / "atmosx-cli.exe", "Syria") == []


# --- the settings only appear when they can do something -------------------------


def test_the_atmosx_settings_hide_unless_that_pack_is_selected() -> None:
    """Settings that quietly do nothing are worse than settings not shown."""
    from game.settings import Settings
    from game.settings.settings import CloudPresetPack

    settings = Settings()
    guarded = {
        name: description
        for name, description in Settings.fields("Campaign Management", "General")
        if name.startswith("atmosx_")
    }
    assert set(guarded) == {
        "atmosx_live_weather",
        "atmosx_cli_path",
        "atmosx_metar_station",
    }

    predicates = []
    for description in guarded.values():
        assert description.visible_when is not None
        predicates.append(description.visible_when)

    settings.cloud_preset_pack = CloudPresetPack.ATMOSX
    assert all(predicate(settings) for predicate in predicates)

    for pack in (
        CloudPresetPack.NONE,
        CloudPresetPack.BANDIT,
        CloudPresetPack.WEATHER2,
    ):
        settings.cloud_preset_pack = pack
        assert not any(predicate(settings) for predicate in predicates)


# --- the observation as the turn's own weather -----------------------------------


def test_the_observation_becomes_the_weather_the_game_reads() -> None:
    """The kneeboard, the active runway and the carrier all read this, not the .miz."""
    weather = LiveWeather("LCLK", parse_preset(PRESET)["vdata"])

    assert round(weather.atmospheric.qnh.mm_hg) == 758
    assert weather.atmospheric.temperature_celsius == 31.0
    assert weather.atmospheric.turbulence_per_10cm == 0.0
    assert weather.wind.at_0m.direction == 350
    assert weather.wind.at_0m.speed == 3.6
    assert weather.wind.at_8000m.speed == 5.4
    # "none" with nothing to draw is a clear sky, which is what the rest of the game
    # understands by no clouds.
    assert weather.clouds is None
    assert weather.fog is None
    assert weather.archetype.id == "clear"


def test_a_named_preset_survives_into_the_model() -> None:
    vdata = parse_preset(PRESET)["vdata"]
    vdata["clouds"] = {
        "preset": "Preset10",
        "base": 2000,
        "thickness": 1200,
        "density": 6,
        "iprecptns": 1,
    }
    weather = LiveWeather("LCLK", vdata)
    assert weather.clouds is not None
    assert weather.clouds.preset is not None
    assert weather.clouds.preset.name == CLOUD_PRESETS["Preset10"].value.name
    assert weather.clouds.base == 2000
    assert weather.clouds.precipitation is PydcsWeather.Preceptions.Rain
    assert weather.archetype.id == "raining"


def test_a_preset_this_dcs_does_not_have_is_not_fatal() -> None:
    """A pack the player has not installed must not take the campaign down with it."""
    vdata = parse_preset(PRESET)["vdata"]
    vdata["clouds"] = {
        "preset": "Preset9999",
        "base": 900,
        "thickness": 0,
        "density": 4,
    }
    weather = LiveWeather("LCLK", vdata)
    assert weather.clouds is not None and weather.clouds.preset is None
    assert weather.clouds.base == 900


def test_the_mission_still_gets_what_the_model_cannot_hold() -> None:
    """visibility distance and dust have nowhere to live but the mission itself."""
    vdata = parse_preset(PRESET)["vdata"]
    vdata["visibility"] = {"distance": 4200}
    vdata["enable_dust"] = True
    vdata["dust_density"] = 3
    mission_weather = Weather("Syria")
    apply_weather(mission_weather, LiveWeather("LCLK", vdata).vdata)
    assert mission_weather.visibility_distance == 4200
    assert mission_weather.enable_dust is True
    assert mission_weather.dust_density == 3


def test_no_observation_leaves_the_turn_with_generated_weather(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import game.weather.atmosxliveweather as module

    monkeypatch.setattr(module, "fetch_observation", lambda theater, settings: None)
    assert module.live_weather_for(object(), object()) is None
