-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the CTLD Plugin including the JTAC Autolase
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------

function spawn_crates()
    --- CrateSpawn script which needs to be run after CTLD was initialized (3s delay)
    env.info("DCSRetribution|CTLD plugin - Spawn crates")
    for _, crate in pairs(dcsRetribution.Logistics.crates) do
        ctld.spawnCrateAtZone(crate.coalition, tonumber(crate.weight), crate.zone)
    end
end

function preload_troops(preload_data)
    --- Troop loading script which needs to be run after CTLD was initialized (5s delay)
    env.info(string.format("DCSRetribution|CTLD plugin - Preloading Troops into %s", preload_data["unit"]))
    ctld.preLoadTransport(preload_data["unit"], preload_data["amount"], true)
end

--- Fixed-wing air assault (the Anubis C-130) never unloaded its troops.
---
--- CTLD's AI auto-unload (ctld.checkAIStatus -> ctld.inDropoffZone) only fires for a
--- transport that is inside a DROPOFF_ZONE *and* on the ground, and ctld.deployTroops
--- additionally gates on landed-or-fast-rope (below 60 ft, under 8 km/h). An air
--- assault by a plane satisfies none of that: the flight plan gives fixed wing no
--- drop-off zone at all (AirAssaultLayout.drop_off is helo-only, so LogisticsInfo
--- carries just the CTLD TARGET_ZONE) and the aircraft overflies the objective at
--- altitude. Its preloaded troops therefore stayed aboard and the flight simply flew
--- through the target and went home.
---
--- Historically the visible drop was the mod's Herc_Soldier_Squad "bomb" released by
--- the CarpetBombing task on the ingress waypoint, with Hercules_Cargo.lua spawning the
--- infantry on S_EVENT_SHOT. That weapon is stripped now -- it triggers the DCS
--- "No input port in scheme: suppress_ballute" crash -- so do the drop here instead:
--- when an AI fixed-wing transport carrying troops reaches its own target zone, spawn
--- the group on the ground beneath it. No parachutes, but the assault lands and
--- captures again, and it works whether or not the Anubis mod is installed.
retribution_airdrops = {}

function retribution_airdrop(unit)
    local onboard = ctld.inTransitTroops[unit:getName()]
    local point = unit:getPoint()
    local ground = { x = point.x, y = land.getHeight({ x = point.x, y = point.z }), z = point.z }
    local dropped = ctld.spawnDroppedGroup(ground, onboard.troops, false)

    -- Mirror ctld.deployTroops' bookkeeping so the dropped group behaves like any
    -- other CTLD insertion (extraction, JTAC lasing, cargo weight, callbacks).
    if onboard.troops.jtac or dropped:getName():lower():find("jtac") then
        local code = table.remove(ctld.jtacGeneratedLaserCodes, 1)
        table.insert(ctld.jtacGeneratedLaserCodes, code)
        ctld.JTACAutoLase(dropped:getName(), code)
    end
    if unit:getCoalition() == 1 then
        table.insert(ctld.droppedTroopsRED, dropped:getName())
    else
        table.insert(ctld.droppedTroopsBLUE, dropped:getName())
    end
    ctld.inTransitTroops[unit:getName()].troops = nil
    ctld.adaptWeightToCargo(unit:getName())
    ctld.processCallback({ unit = unit, unloaded = dropped, action = "dropped_troops" })

    trigger.action.outTextForCoalition(unit:getCoalition(),
        string.format("%s airdropped troops over the objective", unit:getTypeName()), 10)
    env.info(string.format("DCSRetribution|CTLD plugin - airdropped troops from %s", unit:getName()))
end

function retribution_airdrop_check()
    timer.scheduleFunction(retribution_airdrop_check, nil, timer.getTime() + 2)

    for _, drop in pairs(retribution_airdrops) do
        local status, error = pcall(function()
            if drop.done then
                return
            end
            local unit = ctld.getTransportUnit(drop.unit)
            if unit == nil then
                return
            end
            -- Players drop on their own terms via the radio menu.
            if unit:getPlayerName() ~= nil or unit:hasAttribute("Helicopters") then
                return
            end
            if not ctld.troopsOnboard(unit, true) then
                return
            end
            local zone = trigger.misc.getZone(drop.zone)
            if zone == nil then
                return
            end
            local distance = ctld.getDistance(unit:getPoint(), zone.point)
            if distance > zone.radius then
                return
            end
            -- The target zone has a 2.5 km radius, so dropping the moment we cross
            -- into it would leave the infantry a very long walk from the objective.
            -- Wait for the closest approach instead: drop once we are practically
            -- overhead, or as soon as the aircraft starts pulling away again.
            if distance > 500 and (drop.closest == nil or distance < drop.closest) then
                drop.closest = distance
                return
            end
            retribution_airdrop(unit)
            drop.done = true
        end)

        if not status then
            env.error(string.format("DCSRetribution|CTLD plugin - airdrop error: %s", error), false)
        end
    end
end

function toboolean(str) return str == "true" end

-- CTLD plugin - configuration
if dcsRetribution then
    local ctld_pickup_smoke = "none"
    local ctld_dropoff_smoke = "none"

    -- JTACAutoLase specific options
    local autolase = false
    local smoke = false
    local fc3LaserCode = false

    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.ctld then
            env.info("DCSRetribution|CTLD plugin - Setting Up")
            --- Debug Settings
            ctld.Debug = dcsRetribution.plugins.ctld.debug
            ctld.Trace = dcsRetribution.plugins.ctld.debug

            -- Sling loadings settings
            ctld.enableCrates = true
            ctld.slingLoad = dcsRetribution.plugins.ctld.slingload
            ctld.staticBugFix = not dcsRetribution.plugins.ctld.slingload

            --- Special unitLoad Settings as proposed in #2174
            ctld.maximumDistanceLogistic = 300
            ctld.unitLoadLimits = {}
            ctld.unitActions = {}
            for _, transport in pairs(dcsRetribution.Logistics.transports) do
                ctld.unitLoadLimits[transport.aircraft_type] = tonumber(transport.cabin_size)
                ctld.unitActions[transport.aircraft_type] = { crates = toboolean(transport.crates), troops = toboolean(transport.troops) }
            end

            if dcsRetribution.plugins.ctld.smoke then
                ctld_pickup_smoke = "blue"
                ctld_dropoff_smoke = "green"
            end

            -- Definition of spawnable things
            local ctld_troops = ctld.loadableGroups
            ctld.loadableGroups = {
                { name = "Retribution Troops (2)", inf = 2 },
                { name = "Retribution Troops (4)", inf = 4 },
                { name = "Retribution Troops (6)", inf = 4, mg = 1, at = 1 },
                { name = "Retribution Troops (10)", inf = 5, mg = 2, at = 2, aa = 1 },
                { name = "Retribution Troops (12)", inf = 6, mg = 2, at = 2, aa = 2 },
                { name = "Retribution Troops (24)", inf = 12, mg = 4, at = 4, aa = 3, jtac = 1 },
            }
            if dcsRetribution.plugins.ctld.tailorctld then
                --- remove all default CTLD spawning settings
                --- so that we can tailor them for the tasked missions
                ctld.enableSmokeDrop = false
                ctld.enabledRadioBeaconDrop = false
                ctld.spawnableCrates = {}
                ctld.vehiclesForTransportRED = {}
                ctld.vehiclesForTransportBLUE = {}
                ctld.transportPilotNames = {}
                ctld.logisticUnits = {}
                ctld.pickupZones = {}
                ctld.dropOffZones = {}
                ctld.wpZones = {}
            else
                --- append the default CTLD troops
                for _, troop in pairs(ctld_troops) do
                    table.insert(ctld.loadableGroups, troop)
                end
            end

            --- add all carriers as pickup zone
            if dcsRetribution.Carriers then
                for _, carrier in pairs(dcsRetribution.Carriers) do
                    table.insert(ctld.pickupZones, { carrier.unit_name, ctld_pickup_smoke, -1, "yes", 0 })
                end
            end

            --- generate mission specific spawnable crates
            local spawnable_crates = {}
            for _, crate in pairs(dcsRetribution.Logistics.spawnable_crates) do
                table.insert(spawnable_crates, { weight = tonumber(crate.weight), desc = crate.unit, unit = crate.unit })
            end
            ctld.spawnableCrates["Retribution Crates"] = spawnable_crates

            --- Parse the LogisticsInfo for the mission
            for _, item in pairs(dcsRetribution.Logistics.flights) do
                for _, pilot in pairs(item.pilot_names) do
                    table.insert(ctld.transportPilotNames, pilot)
                    if toboolean(item.preload) then
                        local amount = ctld.unitLoadLimits[item.aircraft_type]
                        timer.scheduleFunction(preload_troops, { unit = pilot, amount = amount }, timer.getTime() + 5)
                    end
                end
                if item.pickup_zone then
                    table.insert(ctld.pickupZones, { item.pickup_zone, ctld_pickup_smoke, -1, "yes", tonumber(item.side) })
                end
                if item.drop_off_zone then
                    table.insert(ctld.dropOffZones, { item.drop_off_zone, ctld_dropoff_smoke, tonumber(item.side) })
                end
                if item.target_zone then
                    table.insert(ctld.wpZones, { item.target_zone, "none", "yes", tonumber(item.side) })
                end
                --- An air assault with a target zone but no drop-off zone is a fixed-wing
                --- one, which CTLD cannot unload on its own. See retribution_airdrop.
                if item.target_zone and item.target_zone ~= ""
                        and (item.drop_off_zone == nil or item.drop_off_zone == "") then
                    for _, pilot in pairs(item.pilot_names) do
                        table.insert(retribution_airdrops, { unit = pilot, zone = item.target_zone })
                    end
                end
                if dcsRetribution.plugins.ctld.logisticunit and item.logistic_unit then
                    table.insert(ctld.logisticUnits, item.logistic_unit)
                end
            end

            autolase = dcsRetribution.plugins.ctld.autolase
            env.info(string.format("DCSRetribution|CTLD plugin - JTAC AutoLase enabled = %s", tostring(autolase)))

            if autolase then
                smoke = dcsRetribution.plugins.ctld.jtacsmoke
                env.info(string.format("DCSRetribution|CTLD plugin - JTACAutolase smoke = %s", tostring(smoke)))

                fc3LaserCode = dcsRetribution.plugins.ctld.fc3LaserCode
                env.info(string.format("DCSRetribution|CTLD plugin - JTACAutolase fc3LaserCode = %s", tostring(fc3LaserCode)))

                -- JTAC Autolase configuration code
                for _, jtac in pairs(dcsRetribution.JTACs) do
                    env.info(string.format("DCSRetribution|JTACAutolase - setting up %s", jtac.dcsGroupName))
                    if fc3LaserCode then
                        -- If fc3LaserCode is enabled in the plugin configuration, force the JTAC
                        -- laser code to 1113 to allow lasing for Su-25 Frogfoots and A-10A Warthogs.
                        jtac.laserCode = 1113
                    end
                    ctld.JTACAutoLase(jtac.dcsGroupName, jtac.laserCode, smoke, 'vehicle', nil, { freq = jtac.radio, mod = jtac.modulation, name = jtac.dcsGroupName })
                end
            end
            if dcsRetribution.plugins.ctld.airliftcrates then
                timer.scheduleFunction(spawn_crates, nil, timer.getTime() + 3)
            end
            if #retribution_airdrops > 0 then
                -- After the +5s preload, otherwise a transport already sitting in its
                -- target zone would be checked with an empty cabin and never drop.
                timer.scheduleFunction(retribution_airdrop_check, nil, timer.getTime() + 10)
            end
        end
    end
end
